### ISSUE TITLE
Wrong conversion in cotton

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/crop-information-portal#101]
Probably the conversion from 000 bales to 000 tons is the opposite one. Check if some approximation causes need of data ingestion and check also the GeoBatch internal conversion. 
Fix the update script at https://github.com/geosolutions-it/crop-information-portal/blob/master/updates/sql/align_uom_cotton.sql

charts (000 bales) : 

![image001](https://cloud.githubusercontent.com/assets/1279510/6689622/a0eb5f78-ccbb-11e4-819b-2b81b215fe70.jpg)
Data (in 000 bales):

![image009](https://cloud.githubusercontent.com/assets/1279510/6689623/a5074b4e-ccbb-11e4-9d43-1a10005fd35f.jpg)

Production and yield are not correct. 
```
Y 2000 = 1227.11 (table above from db); > OK
Y 2000 = 35463 (chart); > WRONG
```

**Comment by mircobe87** [comment]
Issue resolved.

The cause of the problem was probably a wrong ingestion: data was multiplied by 1000.
The data were corrected with:
```
update cropdata 
set production = x.value
from (
select *,  production /1000 as value from cropdata  where crop = 'cotton' ) as x
where cropdata.id = x.id
```
and a conversion factor was changed to 1/0.17 = 5.882352941
