### ISSUE TITLE
Agromet - Time Comparsion

### ISSUE THREAD

**Issue by mircobe87** [geosolutions-it/crop-information-portal#108]
To fix and implement:
- [ ] in ratio button group "Mode" replace "Time Comparison" in "Single factor";
- [ ] bring down the chart subtitle to avoid legend overlapping;
- [ ] remove "Season" entry from subtitle;
- [ ] remove "Year" entry from subtitle;

**Comment by offtherailz** [comment]
closed by https://github.com/geosolutions-it/MapStore/commit/f4ea146957f05193f860a620142c115a5ea0c0ee
