### ISSUE TITLE
Islamabad territory is not included in some queries

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/crop-information-portal#125]
Because of the boundary regions changes, some queries do not include islamabad (capital territory) for whole Pakistan. Check all the query to verify that it is included. (look at default parameters in the parametric views and in the mapstore modules). 
To replicate this issue try to generate the chart of the whole pakistan for a commodity, than the same selecting all the provinces. The resoults should be equal but they are not

**Comment by kappu72** [comment]
The client is working correctly, the problem is the provinces list that geoserver uses when there isn't the region_list param.  Pini has more information.
We can close

**Comment by Gnafu** [comment]
Correct, it was only a server-side misconfiguration.
